name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y zsh jq shellcheck git curl
        
    - name: Install Node.js
      run: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        apt-get install -y nodejs
        
    - name: Install Bats
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        ./install.sh /usr/local
        
    - name: Make functions executable
      run: chmod +x autoload/*
      
    - name: Run shellcheck
      run: shellcheck -s bash autoload/*
        
    - name: Test autoload directory
      run: |
        # Verify function files exist and are executable
        [ -f autoload/claude ] && [ -x autoload/claude ]
        [ -f autoload/gemini ] && [ -x autoload/gemini ]
        [ -f autoload/codex ] && [ -x autoload/codex ]
        [ -f autoload/qwen ] && [ -x autoload/qwen ]
        [ -f autoload/brew-list-formulas ] && [ -x autoload/brew-list-formulas ]
        [ -f autoload/hello ] && [ -x autoload/hello ]

        echo "✓ Autoload directory test passed"
        
    - name: Run integration tests
      run: bats tests/integration/